<?php

?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>Real Life Use Cases</title>
</head>

<body class="bg-purple-200">
  <div>
    <button class="mt-6 ml-4 text-5xl">&lt;</button>
    <h1 class="text-2xl absolute font-bold ml-36">Notes</h1>
  </div>

  <h1 class="underline text-4xl mt-20 ml-6">Real Life uses cases</h1>

  <p class="mt-6 mb-6 ml-6">Big data can help you address a range of business
    activities, from customer experience to analytics. Here
    are just a few.
  </p>
  <br>
  <div>
    <p class="mb-2 ml-6">Healthcare:</p>
    <p class="mb-2 ml-6">Giner app uses Big Data for mental health monitoring
      Founded by researches from the Massachusetts Institute
      of Technology, the stratup called Giner.io makes use of
      machine learning technology and Big Data generated by
      smartphones to remotely predict when patients with any
      sorts of mental health issues are symptomatic.
    </p>



  </div>

</body>

</html>