<?php
?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>Real Life Use Cases</title>
</head>

<body class="bg-purple-200">
  <div>
    <button class="mt-6 ml-4 text-5xl">&lt;</button>
    <h1 class="text-2xl absolute font-bold ml-36">Notes</h1>
  </div>
  <h1 class="underline text-4xl mt-20 ml-6">Real Life uses cases</h1>
  <p class="mt-6 mb-6 ml-6">Big data can help you address a range of business
    activities, from customer experience to analytics. Here
    are just a few.
  </p>
  <br>
  <div>
    <p class="mb-2 ml-6">Healthcare:</p>
    <p class="mb-2 ml-6">Giner app uses Big Data for mental health monitoring
    <p class="mb-2 ml-6 mt-6">Giner app uses Big Data for mental health monitoring
      Founded by researches from the Massachusetts Institute
      of Technology, the stratup called Giner.io makes use of
      machine learning technology and Big Data generated by
      smartphones to remotely predict when patients with any
      sorts of mental health issues are symptomatic.
    </p>

    <br>
    <p class="mb-2 ml-6">eCommerce:</p>
    <p class="mb-2 ml-6 mt-6">Amazon analyzes Big Data to enhance its recommender
      engine. It won't come as a surprise that the eCommerce
      and technology giant Amazon collects and analyzes the
      mountain of data about each of the company's
      customers. This could be such information as the
      browsing or purchasing history of a user, demographic
      details, etc. The analysis of this data helps Amazon draw
      a complete picture of each user and create more targeted
      ad campaigns respectively.
    </p>
    <p class="mb-2 ml-6 mt-6">As a result, thanks to the use of Big Data and its on-time
      analytics, Amazon's recommendation engine provides a
      top-notch shopping excperience and encourages
      customers to purchase more products.
    </p>
    <p class="mb-2 ml-6 mt-6">.Additionally, compression, tiering, and deduplication can
      reduce space consumption, as well as cut costs on
      storage. Enterprises also use tools such as Big Data
      Analytics software, Hadoop, NoSQL databases, Spark, Al,
      Machine Learning, Bl applications, etc. to deal with this
      issue.
    </p>
    <p class="mb-2 ml-6 mt-6">One of the most pressing Big Data challenges is storage.
      Data is growing exponentially with time, and with that,
      enterprises are struggling to store these huge sets of
      data. Much of this data is extracted from images, audio,
      documents. text ties. etc. that are unstructured and not in
      databases. It is diffic
    </p>


  </div>


</body>

</html>